[package]
name = "socks5-forwarder"
version = "0.1.0"
authors = ["ihciah <ihciah@gmail.com>"]
edition = "2018"

[dependencies]
tokio-socks = "0.5"
tokio-stream = { version = "0.1", features = ["net"] }
tokio = { version = "1.0", features = ["net", "rt", "rt-multi-thread", "macros"] }
anyhow = "1.0"
clap = "2.33.3"
log = "0.4"
env_logger = "0.8"

[[bin]]
name = "socks5-forwarder"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
